version: '3.7'

services:
  postgres:
    container_name: myapp-postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    image: postgres:12.4
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rails: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/rails server -b 0.0.0.0
    container_name: myapp-rails
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
      TZ: Asia/Tokyo
    links:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/rails-practice
      - bundle:/usr/local/bundle
      - node-modules:/rails-practice/node_modules
    tty: true
    stdin_open: true

  webpack:
    <<: *app
    command: bin/webpack-dev-server
    container_name: myapp-webpack
    ports:
      - 3035:3035
    depends_on:
      - rails
    tty: false
    stdin_open: false

volumes:
  bundle:
    driver: local
  node-modules:
    driver: local
  postgres-data:
    driver: local
